// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfk5Qn-YwJhXJj5Sh3Ubih_60Sb6fIw7I',
    appId: '1:22168881271:web:bc4a2888e162e74e9e9e72',
    messagingSenderId: '22168881271',
    projectId: 'chatapp-3a34a',
    authDomain: 'chatapp-3a34a.firebaseapp.com',
    storageBucket: 'chatapp-3a34a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLCwS8sgERqVEfbIEFmubLpo7aV41HqVU',
    appId: '1:22168881271:android:8d258a28318fe19f9e9e72',
    messagingSenderId: '22168881271',
    projectId: 'chatapp-3a34a',
    storageBucket: 'chatapp-3a34a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmr2dgTnlfHZ-CfGRCvL20JppKh4XxG7w',
    appId: '1:22168881271:ios:d9fc93bb74dcce219e9e72',
    messagingSenderId: '22168881271',
    projectId: 'chatapp-3a34a',
    storageBucket: 'chatapp-3a34a.appspot.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmr2dgTnlfHZ-CfGRCvL20JppKh4XxG7w',
    appId: '1:22168881271:ios:d9fc93bb74dcce219e9e72',
    messagingSenderId: '22168881271',
    projectId: 'chatapp-3a34a',
    storageBucket: 'chatapp-3a34a.appspot.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfk5Qn-YwJhXJj5Sh3Ubih_60Sb6fIw7I',
    appId: '1:22168881271:web:ddc8ea49bd7325f69e9e72',
    messagingSenderId: '22168881271',
    projectId: 'chatapp-3a34a',
    authDomain: 'chatapp-3a34a.firebaseapp.com',
    storageBucket: 'chatapp-3a34a.appspot.com',
  );
}
